### ISSUE TITLE
The VAG API you are using is a puplic API

### ISSUE THREAD

**Issue by BolverBlitz** [madebyfabian/public-transport-app#1]
https://opendata.vag.de/dataset/1db11564-3aa7-458f-9add-7907b434d052/resource/bbf11225-87cc-4abb-bf4b-1a7e2012aaf5/download/schnittstellenbeschreibung-puls-web-api-v1.0.4.pdf

**Comment by madebyfabian** [comment]
Hey, thanks for your message. Yeah, I also discovered that it’s a public api. I just wrote that it isn’t, because I discovered it while using the VAG Website and capturing the network tab.
